### ISSUE TITLE
add surface syntax for V,vin,vproj

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#390] opened 2018-10-12 15:34 UTC

**Comment by ecavallo** [comment] 2018-10-12 18:22
also box.

**Comment by jonsterling** [comment] 2018-10-16 14:10
@ecavallo LOL yeah, so we don't have to use that weird hack

**Comment by favonia** [comment] 2018-10-17 00:31
Closed as duplicate of #148. LOL

**Closed by favonia** 2018-10-17 00:31 UTC
Labels: elaborator, enhancement
